"""Base node class for XML element representation."""

from civ7_modding_tools.nodes.base import BaseNode
from civ7_modding_tools.nodes.action_groups import ActionGroupNode, CriteriaNode
from civ7_modding_tools.nodes.nodes import (
    CivilizationNode,
    CivilizationTraitNode,
    UnitNode,
    UnitStatNode,
    UnitCostNode,
    UnitReplaceNode,
    ConstructibleNode,
    ConstructibleYieldChangeNode,
    EnglishTextNode,
    CityNameNode,
    ProgressionTreeNode,
    ProgressionTreeNodeNode,
    ProgressionTreePrereqNode,
    ModifierNode,
    GameEffectNode,
    RequirementNode,
    StartBiasBiomeNode,
    StartBiasTerrainNode,
    StartBiasAdjacentToCoastNode,
    StartBiasFeatureClassNode,
    StartBiasRiverNode,
    ImportNode,
    VisArtNode,
    VisArtCivilizationBuildingCultureNode,
    VisArtCivilizationUnitCultureNode,
    TraditionNode,
    GreatPersonNode,
    NamedPlaceNode,
    NamedPlaceYieldChangeNode,
    UnitTierVariantNode,
    AdjacencyBonusNode,
    MultiTileBuildingNode,
    UniqueQuarterNode,
    LeaderUnlockNode,
    ModifierRequirementNode,
    StringNode,
    ArgumentNode,
    VisualRemapRowNode,
    VisualRemapRootNode,
)
from civ7_modding_tools.nodes.database import (
    DatabaseNode,
    KindNode,
    TypeNode,
    TagNode,
    TypeTagNode,
    TraitNode,
    TraitModifierNode,
    CivilizationItemNode,
    CivilizationTagNode,
    BuildingNode,
    ImprovementNode,
    ConstructibleValidDistrictNode,
    ConstructibleValidBiomeNode,
    ConstructibleValidFeatureNode,
    ConstructibleValidTerrainNode,
    ConstructibleValidResourceNode,
    ConstructibleMaintenanceNode,
    ConstructiblePlunderNode,
    ConstructibleAdvisoryNode,
    ConstructibleAdjacencyNode,
    WarehouseYieldChangeNode,
    ConstructibleWarehouseYieldNode,
    UnlockNode,
    UnlockRewardNode,
    UnlockRequirementNode,
    UnlockConfigurationValueNode,
    RequirementSetNode,
    RequirementArgumentNode,
    RequirementSetRequirementNode,
    ModifierNode,
    GameModifierNode,
    ModifierStringNode,
    ArgumentNode,
    ProgressionTreeAdvisoryNode,
    ProgressionTreeNodeUnlockNode,
    ProgressionTreeQuoteNode,
    TraditionModifierNode,
    LeaderUnlockNode,
    LeaderCivilizationBiasNode,
    DistrictFreeConstructibleNode,
    StartBiasResourceNode,
    UnitUpgradeNode,
    UnitAdvisoryNode,
    UniqueQuarterModifierNode,
    CivilizationUnlockNode,
    LegacyCivilizationNode,
    LegacyCivilizationTraitNode,
    LegacyIndependentsUpdateNode,
    UpdateWhereNode,
    UpdateSetNode,
    VisualRemapNode,
    IconDefinitionNode,
    AiListTypeNode,
    AiListNode,
    AiFavoredItemNode,
    LeaderCivPriorityNode,
    LoadingInfoCivilizationNode,
    CivilizationFavoredWonderNode,
)

__all__ = [
    "BaseNode",
    "DatabaseNode",
    # Action Groups (R4)
    "ActionGroupNode",
    "CriteriaNode",
    # Civilization
    "CivilizationNode",
    "CivilizationTraitNode",
    "CivilizationItemNode",
    "CivilizationTagNode",
    "CivilizationUnlockNode",
    "LegacyCivilizationNode",
    "LegacyCivilizationTraitNode",
    "LegacyIndependentsUpdateNode",
    "UpdateWhereNode",
    "UpdateSetNode",
    # Units
    "UnitNode",
    "UnitStatNode",
    "UnitCostNode",
    "UnitReplaceNode",
    "UnitUpgradeNode",
    "UnitAdvisoryNode",
    # Constructibles
    "ConstructibleNode",
    "ConstructibleYieldChangeNode",
    "BuildingNode",
    "ImprovementNode",
    "ConstructibleValidDistrictNode",
    "ConstructibleValidBiomeNode",
    "ConstructibleValidFeatureNode",
    "ConstructibleValidTerrainNode",
    "ConstructibleValidResourceNode",
    "ConstructibleMaintenanceNode",
    "ConstructiblePlunderNode",
    "ConstructibleAdvisoryNode",
    "ConstructibleAdjacencyNode",
    "ConstructibleWarehouseYieldNode",
    # Adjacency
    "WarehouseYieldChangeNode",
    # Text/Icons
    "EnglishTextNode",
    "CityNameNode",
    "IconDefinitionNode",
    "VisualRemapNode",
    "VisualRemapRowNode",
    "VisualRemapRootNode",
    # Progression Trees
    "ProgressionTreeNode",
    "ProgressionTreeNodeNode",
    "ProgressionTreePrereqNode",
    "ProgressionTreeAdvisoryNode",
    "ProgressionTreeNodeUnlockNode",
    "ProgressionTreeQuoteNode",
    # Types/Tags
    "KindNode",
    "TypeNode",
    "TagNode",
    "TypeTagNode",
    "TraitNode",
    "TraitModifierNode",
    # Modifiers/Effects
    "ModifierNode",
    "ModifierRequirementNode",
    "GameEffectNode",
    "GameModifierNode",
    "ModifierStringNode",
    "ArgumentNode",
    # Requirements
    "RequirementNode",
    "RequirementSetNode",
    "RequirementArgumentNode",
    "RequirementSetRequirementNode",
    # Unlocks
    "UnlockNode",
    "UnlockRewardNode",
    "UnlockRequirementNode",
    "UnlockConfigurationValueNode",
    # Traditions
    "TraditionNode",
    "TraditionModifierNode",
    # Great People
    "GreatPersonNode",
    # Named Places
    "NamedPlaceNode",
    "NamedPlaceYieldChangeNode",
    # Advanced Unit & Building Features (Phase 5)
    "UnitTierVariantNode",
    "AdjacencyBonusNode",
    "MultiTileBuildingNode",
    # Leaders
    "LeaderUnlockNode",
    "LeaderCivilizationBiasNode",
    # AI Configuration
    "AiListTypeNode",
    "AiListNode",
    "AiFavoredItemNode",
    "LeaderCivPriorityNode",
    "LoadingInfoCivilizationNode",
    "CivilizationFavoredWonderNode",
    # Districts
    "DistrictFreeConstructibleNode",
    # Start Biases
    "StartBiasBiomeNode",
    "StartBiasTerrainNode",
    "StartBiasResourceNode",
    "StartBiasAdjacentToCoastNode",
    "StartBiasFeatureClassNode",
    "StartBiasRiverNode",
    # Unique Quarters
    "UniqueQuarterNode",
    "UniqueQuarterModifierNode",
    # Visual Art
    "VisArtNode",
    "VisArtCivilizationBuildingCultureNode",
    "VisArtCivilizationUnitCultureNode",
    # Other
    "ImportNode",
    "StringNode",
]
